dist: xenial
sudo: false
language: python
cache: pip
python:
- '3.6'
script: true
deploy:
  provider: pypi
  user: kyle0x54
  password:
    secure: zDhc23ZJUVtaVrWaO2X8CfKZuqBItJdkWQv3Uvk7es+GP/7Q+ADj2Lv2GxIPoWesMQ0BPEdc3oGjKvWTZa/lxWC63tt9EuHrjF9aMkhyN6BaOxob85jDfRLQJ1aOL5Hfaws5OdwnWrKk/TtsLlL3miiXEkecoJnwRavx64sYWRXIEkio1PaxMddjDJFj1PjfvrpvnNO2j+qnkDVF/05Vj+bQZtHuBAbeO12TJ8RZOP7ZKQjTTvuQcTEMbv/S8LTJpv3XKtPvIDc3gQhBhkW5Gp/cU1dsNFMOA+V6yxGhSsag7JyJf4VRMVPx7wEMG+9YNioT/nkvt4Q12x1cBcr99lE2xg61Ai9BLS6u4ttFtCSHyDh1Di1M35UFmWD2zjCLLTp4i+qNBGo4CJFTLL7NFaanyW9taauW7dfQIH3XbI67vPct1BlIXcyqAQnfU8vwQOXkJOLe/FyXo3c6i75Tx2sdeaectSWzaV5KmKjmsNfUq+Qy1LlY5nJcL34vDNzaBAJqQF1VmKkz6OY4nsPZK2mIfqzw3roBFwgO+hT2MRf1e8b8YPpgLnpXrYFz+bqqx6p2yQ12JE8M28uJ4TTHTkc8Hk7XyWNtluUzlBEn0ehT9uXYj9UgKijX+kF8UA9exI3/4Y0FWlTAJYagQ59lFKV+JPNqZ/L6YyN5YAgf6iE=
  true:
    branch: master
    tags: true
    python: '3.6'
    distributions: sdist bdist_wheel
    skip_existing: true
    skip_cleanup: true
    skip_upload_docs: true
